default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 6 } %>

#code_bi_development:

development:
  <<: *default
  database: talk_talk_development

test:
  <<: *default
  database: talk_talk_test

